/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bridge_pillar.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0.75]}>
        <mesh geometry={nodes.Mesh_bridge_pillar.geometry} material={materials.asphalt} />
        <mesh geometry={nodes.Mesh_bridge_pillar_1.geometry} material={materials.pavement} />
      </group>
    </group>
  )
}

useGLTF.preload('/bridge_pillar.glb')
